// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package models

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// Label defines model for Label.
type Label struct {
	// Description Description of the label
	Description *string `json:"description,omitempty"`

	// Name Name of the label
	Name *string `json:"name,omitempty"`
}

// ListLabelsResponse defines model for ListLabelsResponse.
type ListLabelsResponse struct {
	Data       *[]Label    `json:"data,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// NewLabel defines model for NewLabel.
type NewLabel struct {
	// Description Description of the label
	Description *string `json:"description,omitempty"`

	// Name Name of the label
	Name string `json:"name"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// Page current page number
	Page *int64 `json:"page,omitempty"`

	// PageSize maximum number of items per page
	PageSize *int `json:"page_size,omitempty"`

	// TotalItems total number of items
	TotalItems *int64 `json:"total_items,omitempty"`

	// TotalPages total number of pages
	TotalPages *int64 `json:"total_pages,omitempty"`
}

// ListLabelsParams defines parameters for ListLabels.
type ListLabelsParams struct {
	// Page page number
	Page *int64 `form:"page,omitempty" json:"page,omitempty"`

	// PageSize maximum number of labels to return
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// CreateLabelJSONRequestBody defines body for CreateLabel for application/json ContentType.
type CreateLabelJSONRequestBody = NewLabel
