// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package models

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// Label defines model for Label.
type Label struct {
	// Description Description of the label
	Description *string `json:"description,omitempty"`

	// Name Name of the label
	Name *string `json:"name,omitempty"`
}

// NewLabel defines model for NewLabel.
type NewLabel struct {
	// Description Description of the label
	Description *string `json:"description,omitempty"`

	// Name Name of the label
	Name string `json:"name"`
}

// CreateLabelJSONRequestBody defines body for CreateLabel for application/json ContentType.
type CreateLabelJSONRequestBody = NewLabel
