// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package models

// BoundingBox defines model for BoundingBox.
type BoundingBox struct {
	// Height height of the bounding box
	Height float32 `json:"height"`

	// Id ID of the bounding box
	Id string `json:"id"`

	// Label label
	Label string `json:"label"`

	// Width width of the bounding box
	Width float32 `json:"width"`

	// Xc x coordinate of the center point
	Xc float32 `json:"xc"`

	// Yc y coordinate of the center point
	Yc float32 `json:"yc"`
}

// Collection defines model for Collection.
type Collection struct {
	// Description Description of the collection
	Description *string `json:"description,omitempty"`

	// Name Name of the collection
	Name *string `json:"name,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// Image defines model for Image.
type Image struct {
	BoundingBoxes *[]BoundingBox `json:"bounding_boxes,omitempty"`

	// Collection name of collection in which the image belongs
	Collection string `json:"collection"`

	// Id ID of the image
	Id     string    `json:"id"`
	Labels *[]string `json:"labels,omitempty"`
}

// ImageIngestionResponse defines model for ImageIngestionResponse.
type ImageIngestionResponse struct {
	// Id ID of ingested image
	Id *string `json:"id,omitempty"`
}

// Label defines model for Label.
type Label struct {
	// Description Description of the label
	Description *string `json:"description,omitempty"`

	// Name Name of the label
	Name *string `json:"name,omitempty"`
}

// ListCollectionsResponse defines model for ListCollectionsResponse.
type ListCollectionsResponse struct {
	Data       *[]Collection `json:"data,omitempty"`
	Pagination Pagination    `json:"pagination"`
}

// ListImagesResponse defines model for ListImagesResponse.
type ListImagesResponse struct {
	Images     []Image    `json:"images"`
	Pagination Pagination `json:"pagination"`
}

// ListLabelsResponse defines model for ListLabelsResponse.
type ListLabelsResponse struct {
	Data       *[]Label   `json:"data,omitempty"`
	Pagination Pagination `json:"pagination"`
}

// NewBoundingBox defines model for NewBoundingBox.
type NewBoundingBox struct {
	// Height height of the bounding box
	Height float32 `json:"height"`

	// Label label
	Label string `json:"label"`

	// Width width of the bounding box
	Width float32 `json:"width"`

	// Xc x coordinate of the center point
	Xc float32 `json:"xc"`

	// Yc y coordinate of the center point
	Yc float32 `json:"yc"`
}

// NewCollection defines model for NewCollection.
type NewCollection struct {
	// Description Description of the collection
	Description *string `json:"description,omitempty"`

	// Name Name of the collection
	Name string `json:"name"`
}

// NewImage defines model for NewImage.
type NewImage struct {
	BoundingBoxes *[]NewBoundingBox `json:"bounding_boxes,omitempty"`

	// Collection name of collection in which to add the image
	Collection string `json:"collection"`

	// Data base64 encoded image raw bytes
	Data   string    `json:"data"`
	Labels *[]string `json:"labels,omitempty"`
}

// NewLabel defines model for NewLabel.
type NewLabel struct {
	// Description Description of the label
	Description *string `json:"description,omitempty"`

	// Name Name of the label
	Name string `json:"name"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// Page current page number
	Page int64 `json:"page"`

	// PageSize maximum number of items per page
	PageSize int `json:"page_size"`

	// TotalItems total number of items
	TotalItems int64 `json:"total_items"`

	// TotalPages total number of pages
	TotalPages int64 `json:"total_pages"`
}

// ListCollectionsParams defines parameters for ListCollections.
type ListCollectionsParams struct {
	// Page page number
	Page *int64 `form:"page,omitempty" json:"page,omitempty"`

	// PageSize maximum number of collections to return
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListImagesParams defines parameters for ListImages.
type ListImagesParams struct {
	// Page page number
	Page *int64 `form:"page,omitempty" json:"page,omitempty"`

	// PageSize maximum number of collections to return
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Collection name of collection
	Collection *string `form:"collection,omitempty" json:"collection,omitempty"`
}

// ListLabelsParams defines parameters for ListLabels.
type ListLabelsParams struct {
	// Page page number
	Page *int64 `form:"page,omitempty" json:"page,omitempty"`

	// PageSize maximum number of labels to return
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// CreateCollectionJSONRequestBody defines body for CreateCollection for application/json ContentType.
type CreateCollectionJSONRequestBody = NewCollection

// IngestImageJSONRequestBody defines body for IngestImage for application/json ContentType.
type IngestImageJSONRequestBody = NewImage

// CreateLabelJSONRequestBody defines body for CreateLabel for application/json ContentType.
type CreateLabelJSONRequestBody = NewLabel
